DROP SEQUENCE USER_SEQ;
DROP SEQUENCE POST_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP TABLE COMMENTS CASCADE CONSTRAINTS ;
DROP TABLE POST CASCADE CONSTRAINTS ;
DROP TABLE CATEGORY CASCADE CONSTRAINTS ;
DROP TABLE BLOG CASCADE CONSTRAINTS ;
DROP TABLE BLOG_USER CASCADE CONSTRAINTS ;

-- BLOG USER
CREATE TABLE BLOG_USER (
USER_NO       NUMBER(10)    NOT NULL,
USER_ID       VARCHAR2(32)  NOT NULL,
USER_NAME     VARCHAR2(100) NOT NULL,
ROLE          VARCHAR2(32)  NOT NULL,
PASSWORD      VARCHAR2(28), 
CREATED_DATE  DATE,
MODIFIED_DATE DATE,
PRIMARY KEY ( USER_NO ) 
);   

-- BLOG
CREATE TABLE BLOG
(
BLOG_NO NUMBER(10) NOT NULL ,
TITLE VARCHAR2(100) NOT NULL,
TAG VARCHAR2(500),
CNT_DISPLAY_POST NUMBER,
STATUS VARCHAR2(20),
FILE_NAME VARCHAR2(20),
CONSTRAINT PK_BLOG PRIMARY KEY (BLOG_NO),
CONSTRAINT FK_BLOG_BLOG_NO FOREIGN KEY (BLOG_NO) REFERENCES BLOG_USER(USER_NO) ON DELETE CASCADE 
);

-- CATEGORY
CREATE TABLE CATEGORY
(
BLOG_NO NUMBER(10) NOT NULL ,
CATEGORY_NO VARCHAR2(10) NOT NULL ,
CATEGORY_NAME VARCHAR2(500) NOT NULL ,
DISPLAY_TYPE VARCHAR2(10) NOT NULL,
CNT_DISPLAY_POST NUMBER NOT NULL,
DESCRIPTION VARCHAR2(1000) ,
CREATED_DATE DATE,
MODIFIED_DATE DATE,
CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_NO)
);

-- POST
CREATE TABLE POST
(
POST_NO NUMBER(10) NOT NULL,
CATEGORY_NO VARCHAR2(10) NOT NULL,
TITLE   VARCHAR2(500) NOT NULL,
CONTENT VARCHAR2(1000),
CREATED_DATE  DATE,
MODIFIED_DATE DATE,
CONSTRAINT PK_POST PRIMARY KEY (POST_NO),
CONSTRAINT FK_POST_CATEGORY_NO  FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO) ON DELETE CASCADE
);

-- COMMENTS
CREATE TABLE COMMENTS
(
COMMENTS_NO NUMBER(10) NOT NULL ,
POST_NO NUMBER(10) NOT NULL,
CONTENT VARCHAR2(1000),
CREATED_DATE DATE,
CONSTRAINT PK_REPLY PRIMARY KEY (COMMENTS_NO),
CONSTRAINT FK_REPLY_POST_NO FOREIGN KEY(POST_NO) REFERENCES POST(POST_NO) ON DELETE CASCADE
);

-- USER_SEQ
CREATE SEQUENCE USER_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999
NOCACHE
NOCYCLE;

-- POST_SEQ
CREATE SEQUENCE POST_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999
NOCACHE
NOCYCLE;

-- COMMENTS_SEQ
CREATE SEQUENCE COMMENTS_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999
NOCACHE
NOCYCLE;

INSERT INTO BLOG_USER (USER_NO, USER_ID, USER_NAME,ROLE,PASSWORD,CREATED_DATE,MODIFIED_DATE)
VALUES(USER_SEQ.nextval, 'admin', '관리자', 'Admin', '1234',sysdate, sysdate);

INSERT INTO BLOG_USER (USER_NO,USER_ID, USER_NAME,ROLE,PASSWORD,CREATED_DATE,MODIFIED_DATE)
VALUES(USER_SEQ.nextval,'kickscar', '안대혁', 'User', '1234',sysdate, sysdate);

INSERT INTO BLOG_USER (USER_NO,USER_ID, USER_NAME,ROLE,PASSWORD,CREATED_DATE,MODIFIED_DATE)
VALUES(USER_SEQ.nextval, 'dooly','둘리', 'User', '1234', sysdate, sysdate);
--테스트 데이터
INSERT INTO BLOG (BLOG_NO, TITLE, TAG, CNT_DISPLAY_POST, STATUS, FILE_NAME) 
		   VALUES(3, 'firstBlog', '여행#낚시#', 1, 1,'');
INSERT INTO CATEGORY (BLOG_NO, CATEGORY_NO, CATEGORY_NAME,DISPLAY_TYPE, CNT_DISPLAY_POST, DESCRIPTION, CREATED_DATE, MODIFIED_DATE) 
		       VALUES(3, '1', '여행','TYPE', 1, '잘못만듬', SYSDATE, SYSDATE);
INSERT INTO POST (POST_NO, CATEGORY_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) 
		       VALUES(1, '1', '여행','국내여행', SYSDATE, SYSDATE);
INSERT INTO POST (POST_NO, CATEGORY_NO, TITLE, CONTENT, CREATED_DATE, MODIFIED_DATE) 
		       VALUES(2, '1', '여행2','국내여행2', SYSDATE, SYSDATE);			   
INSERT INTO COMMENTS (COMMENTS_NO, CONTENT, CREATED_DATE, POST_NO) 
		       VALUES(1, '잘봣습니다', SYSDATE, 1);	
		   


COMMIT;